### ISSUE TITLE
Tenant does not exist error

### ISSUE THREAD

**Issue by angelokimhui** [progrium/authsite#1]
I tried recreating a new tenant and the problem still persists.

![image](https://github.com/user-attachments/assets/51bc8ad0-791f-4c80-86a4-3553aec97703)

**Comment by turbolego** [comment]
I have the same error.
The steps for logging into GitHub and 0Auth seems to work, but stops on the step:

> ┃ We are about to reset and configure the Auth0 tenant 'turbolego'.
> ┃ Are you sure you want to continue?

Brand new repository used for this, has no files only custom domain setup.

> PS C:\Users\Tobias Andersen\IdeaProjects\authsite> ./authsite musikkunderstjernene.online
> ✓ Domain 'musikkunderstjernene.online' is properly pointing to GitHub Pages.
> ✓ Logged into Auth0 with tenant 'turbolego' to be configured.
> ✓ Logged into GitHub as 'turbolego'.
> 2024/09/04 12:35:27 conn create:409 Conflict: A connection with the same name is being deleted, try again later
> 
> PS C:\Users\Tobias Andersen\IdeaProjects\authsite> ./authsite musikkunderstjernene.online
> ✓ Domain 'musikkunderstjernene.online' is properly pointing to GitHub Pages.
> ✓ Logged into Auth0 with tenant 'turbolego' to be configured.
> ✓ Logged into GitHub as 'turbolego'.
> 2024/09/04 12:38:10 update binding:404 Not Found: Tenant does not exist.
> 
> PS C:\Users\Tobias Andersen\IdeaProjects\authsite> ./authsite musikkunderstjernene.online
> ✓ Domain 'musikkunderstjernene.online' is properly pointing to GitHub Pages.
> ✓ Logged into Auth0 with tenant 'turbolego' to be configured.
> ✓ Logged into GitHub as 'turbolego'.
> 2024/09/04 12:41:46 conn create:409 Conflict: A connection with the same name is being deleted, try again later
>

**Comment by progrium** [comment]
Looks like we just need to make sure it retries. There was another step where this came up, so this should be a quick fix. In fact, should be an easy PR for either of you if I don't get back to this soon.

**Comment by turbolego** [comment]
> Looks like we just need to make sure it retries. There was another step where this came up, so this should be a quick fix. In fact, should be an easy PR for either of you if I don't get back to this soon.

EDIT: I fixed the `panic: open site\auth\api.js: file does not exist` -error too, PR updated: https://github.com/progrium/authsite/pull/2

😄 

welp, i was able to get past the `Tenant does not exist` error, but now i have a new error `panic: open site\auth\api.js: file does not exist` which makes no sense haha

I made a PR: https://github.com/progrium/authsite/pull/2

**Comment by progrium** [comment]
@angelokimhui that PR was merged so hopefully it resolves the issue!
